# Generated by Django 3.2.3 on 2021-05-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_like_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='like_genres',
            new_name='like_users',
        ),
    ]
