# Generated by Django 3.2.3 on 2021-05-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movie_title_location_movie_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='movie_pk',
            new_name='movie',
        ),
    ]
