# Generated by Django 3.2.3 on 2021-05-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movie_pk_location_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcomment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
